#!/usr/bin/env bash

export DOTFILES=$HOME/dotfiles
export WORK_FOLDERS="bin,trayio,personal,zsh,git"
export PERSONAL_FOLDERS="git,bin,zsh,personal,stow" # add more folders when needed

pushd $DOTFILES >/dev/null

case $1 in
work | trayio)
    folders=$WORK_FOLDERS
    ;;
personal)
    folders=$PERSONAL_FOLDERS
    ;;
*)
    echo "Invalid group"
    exit 1
    ;;
esac

case $2 in
clean | delete | wipe)
    command=-D
    wording="Unstowing"
    ;;
install)
    command=-R
    wording="Stowing"
    ;;
*)
    echo "Invalid group"
    exit 1
    ;;
esac

for folder in $(echo $folders | sed "s/,/ /g"); do
    echo -n "$wording $folder...  "
    output=$(stow $command $folder 2>&1)
    result=$?
    if [ $result -eq 0 ]; then
        echo "ok"
    else
        echo "ERROR: $output"
    fi
done

popd >/dev/null
